# syntax=docker/dockerfile:1

FROM python:3.11.3
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .

CMD ["python3", "-m", "alembic", "upgrade", "head"]
CMD ["python3", "-m", "uvicorn", "build_your_own_adventure_api.main:app", "--host=0.0.0.0", "--port=8080"]
