# fly.toml file generated for build-your-own-adventure-backend on 2023-05-20T14:00:53-07:00

app = "build-your-own-adventure-backend"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "sea"
processes = []

[build]
  dockerfile = "Dockerfile.api"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
